{
 "title": "Docker Overview - (Datadog Clone)",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "server", "label": "Server", "query": "label_values(up, server)" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"display: flex; align-items: center; justify-content: center; height: 100%; width: 100%; margin: 0; padding: 0; overflow: hidden;\">\n  <img src=\"/public/img/custom/docker-icon.svg\" style=\"height: 80%; width: auto; object-fit: contain;\" />\n</div>"
   }
  },
  {
   "title": "Docker CPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{server=\"$server\", name!=\"\"}[1m])) / count(node_cpu_seconds_total{server=\"$server\", mode=\"system\"})) * 100"
    }
   ]
  },
  {
   "title": "Docker Network Traffic",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{server=\"$server\", device!~\"lo|veth.*\"}[1m]) + rate(container_network_transmit_bytes_total{server=\"$server\", device!~\"lo|veth.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "UP Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{server=\"$server\", name!=\"\"})",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(container_start_time_seconds{server=\"$server\", name!=\"\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Container Density by Image",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "count by (image) (container_last_seen{server=\"$server\", image!=\"\"})"
    }
   ]
  },
  {
   "title": "Docker RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{server=\"$server\", name!=\"\"})"
    }
   ]
  },
  {
   "title": "Avg. Container Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(time() - container_start_time_seconds{server=\"$server\", name!=\"\"})"
    }
   ]
  },
  {
   "title": "Crashes (OOM)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(container_oom_events_total{server=\"$server\"}[$__range]))"
    }
   ]
  },
  {
   "title": "CPU - Most CPU-intensive containers",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (name) (rate(container_cpu_usage_seconds_total{server=\"$server\", name!=\"\"}[1m]) * 100))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU - Core Load (User/System)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_user_seconds_total{server=\"$server\"}[1m])) * 100",
     "legendFormat": "User"
    },
    {
     "expr": "sum(irate(container_cpu_system_seconds_total{server=\"$server\"}[1m])) * 100",
     "legendFormat": "System"
    }
   ]
  },
  {
   "title": "CPU system by image",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (image) (rate(container_cpu_system_seconds_total{server=\"$server\", image!=\"\"}[1m]) * 100)",
     "legendFormat": "{{image}}"
    }
   ]
  },
  {
   "title": "CPU user by image",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (container_label_com_docker_compose_service) (rate(container_cpu_user_seconds_total{server=\"$server\", container_label_com_docker_compose_service!=\"\"}[1m]) * 100)",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "CPU by container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(container_cpu_usage_seconds_total{server=\"$server\", name!=\"\"}[1m]) * 100)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "MEMORY - Most RAM-intensive containers",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (name) (container_memory_usage_bytes{server=\"$server\", name!=\"\"}))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "MEMORY - Cache Memory by Image",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (image) (container_memory_cache{server=\"$server\", image!=\"\"})",
     "legendFormat": "{{image}}"
    }
   ]
  },
  {
   "title": "MEMORY - RSS Memory by Image",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (image) (container_memory_rss{server=\"$server\", image!=\"\"})",
     "legendFormat": "{{image}}"
    }
   ]
  },
  {
   "title": "MEMORY - Memory by Container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{server=\"$server\", name!=\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Swap by image",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (image) (container_memory_swap{server=\"$server\", image!=\"\"})",
     "legendFormat": "{{image}}"
    }
   ]
  },
  {
   "title": "NETWORK - Most TX-intensive containers",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (name) (irate(container_network_transmit_bytes_total{server=\"$server\", name!=\"\", device!~\"lo|veth.*\"}[1m])))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Avg. rx bytes by image",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (image) (irate(container_network_receive_bytes_total{server=\"$server\", image!=\"\"}[1m]))",
     "legendFormat": "RX: {{image}}"
    }
   ]
  },
  {
   "title": "NETWORK - TX by Container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (name) (irate(container_network_transmit_bytes_total{server=\"$server\", name!=\"\"}[1m]))",
     "legendFormat": "TX: {{name}}"
    }
   ]
  },
  {
   "title": "NETWORK - Most RX-intensive containers",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (name) (irate(container_network_receive_bytes_total{server=\"$server\", name!=\"\", device!~\"lo|veth.*\"}[1m])))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Avg. tx bytes by image",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (image) (irate(container_network_transmit_bytes_total{server=\"$server\", image!=\"\"}[1m]))",
     "legendFormat": "TX: {{image}}"
    }
   ]
  },
  {
   "title": "NETWORK - HTTP Errors (4xx/5xx)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(container_network_receive_errors_total{server=\"$server\", name!=\"\"}[1m]) + rate(container_network_transmit_errors_total{server=\"$server\", name!=\"\"}[1m]))",
     "legendFormat": "Errors: {{name}}"
    }
   ]
  },
  {
   "title": "I/O - Most Write-intensive containers",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (name) (irate(container_fs_writes_bytes_total{server=\"$server\", name!=\"\"}[1m])))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Avg. I/O bytes written by image",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (image) (irate(container_fs_writes_bytes_total{server=\"$server\", image!=\"\"}[1m]))",
     "legendFormat": "Write: {{image}}"
    }
   ]
  },
  {
   "title": "I/O - Write Operations (IOPS)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(container_fs_writes_total{server=\"$server\", name!=\"\"}[1m]))",
     "legendFormat": "Writes: {{name}}"
    }
   ]
  },
  {
   "title": "I/O - Most Read-intensive containers",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (name) (irate(container_fs_reads_bytes_total{server=\"$server\", name!=\"\"}[1m])))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Avg. I/O bytes read by image",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (container_label_com_docker_compose_service) (irate(container_fs_reads_bytes_total{server=\"$server\", container_label_com_docker_compose_service!=\"\"}[1m]))",
     "legendFormat": "Read: {{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "I/O - Read Operations (IOPS)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(container_fs_reads_total{server=\"$server\", name!=\"\"}[1m]))",
     "legendFormat": "Reads: {{name}}"
    }
   ]
  }
 ]
}