{
 "title": "MYSQL (Datadog Clone)",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"display: flex; align-items: center; justify-content: center; height: 100%; width: 100%;\">\n  <img src=\"/public/img/custom/-icon.svg\" style=\"height: 80%; object-fit: contain;\" />\n</div>"
   }
  },
  {
   "title": "Failed Connects",
   "type": "stat",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_aborted_connects"
    }
   ]
  },
  {
   "title": "Connections to Server - Rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_threads_connected[5m])"
    }
   ]
  },
  {
   "title": "Connections - Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_threads_connected"
    }
   ]
  },
  {
   "title": "Slow Query - Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_slow_queries[5m])"
    }
   ]
  },
  {
   "title": "Select Queries - Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"select\"}[5m])"
    }
   ]
  },
  {
   "title": "Insert Queries - Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"insert\"}[5m])"
    }
   ]
  },
  {
   "title": "Update Queries - Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 19 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"update\"}[5m])"
    }
   ]
  },
  {
   "title": "Delete Queries - Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"delete\"}[5m])"
    }
   ]
  },
  {
   "title": "Query Runtime - Avg",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_queries[5m]) / rate(mysql_global_status_uptime[5m])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 25 },
   "options": {
    "content": "> The current rate of queries will naturally rise and fall, and as such it's not always an actionable metric based on fixed thresholds."
   }
  },
  {
   "title": "Running - Threads",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "mysql_global_status_threads_running"
    }
   ]
  },
  {
   "title": "Connected - Threads",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 29 },
   "targets": [
    {
     "expr": "mysql_global_status_threads_connected"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 29 },
   "options": {
    "content": "Most of the metrics and monitoring strategies outlined here also apply to MySQL-compatible technologies such as MariaDB and Percona Server."
   }
  },
  {
   "title": "Cache Utilization Ratio",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "(mysql_global_status_threads_created / mysql_global_status_connections) * 100"
    }
   ]
  },
  {
   "title": "Data Reads/Writes - Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 35 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_innodb_data_reads[5m])",
     "legendFormat": "Reads"
    },
    {
     "expr": "rate(mysql_global_status_innodb_data_writes[5m])",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "InnoDB Buffer Pool",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "mysql_global_variables_innodb_buffer_pool_size"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 39 },
   "options": {
    "content": "InnoDB is the storage management system for both MariaDB and MySQL."
   }
  },
  {
   "title": "InnoDB Buffer Pool Pages",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 41 },
   "targets": [
    {
     "expr": "mysql_global_status_innodb_buffer_pool_pages_total"
    }
   ]
  },
  {
   "title": "System memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 43 },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes"
    }
   ]
  },
  {
   "title": "CPU usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "System load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 47 },
   "targets": [
    { "expr": "node_load1", "legendFormat": "1m" },
    { "expr": "node_load5", "legendFormat": "5m" }
   ]
  },
  {
   "title": "Network traffic (per sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total[5m])",
     "legendFormat": "Received"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total[5m]) * -1",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "{job=\"mysql\"} |= \"error\""
    }
   ]
  },
  {
   "title": "All Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 61 },
   "targets": [
    {
     "expr": "{job=\"mysql\"}"
    }
   ]
  }
 ]
}