{
 "title": "docker_overview",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "server", "label": "Server", "query": "label_values(up, server)" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": {
    "content": "<div style=\"display: flex; align-items: center; justify-content: center; height: 100%; width: 100%; margin: 0; padding: 0; overflow: hidden;\">\n  <img src=\"https://www.svgrepo.com/show/448221/docker.svg\" style=\"height: 80%; width: auto; object-fit: contain;\" />\n</div>"
   }
  },
  {
   "title": "Containers - CPU Usage",
   "type": "table",
   "description": "Ranking completo de consumo de CPU respecto a la capacidad total del host. Haz clic en el nombre para ver detalles.",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by (name) (rate(container_cpu_usage_seconds_total{server=\"$server\", name!=\"\", container!=\"POD\"}[$__rate_interval])) / scalar(count(node_cpu_seconds_total{server=\"$server\", mode=\"idle\"}))) * 100"
    }
   ]
  },
  {
   "title": "Containers - Memory Usage",
   "type": "table",
   "description": "Ranking completo de consumo de RAM respecto al total del host. Haz clic en el nombre para ver detalles o en el encabezado para ordenar.",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by (name) (avg_over_time(container_memory_working_set_bytes{server=\"$server\", name!=\"\", container!=\"POD\"}[$__interval])) / on() group_left() machine_memory_bytes{server=\"$server\"}) * 100"
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_tasks_state{server=\"$server\", name!=\"\", state=\"running\", container!=\"POD\"}) - count(container_last_seen{server=\"$server\", name!=\"\", container!=\"POD\"}) + count(container_tasks_state{server=\"$server\", name!=\"\", state=\"running\", container!=\"POD\"})"
    }
   ]
  },
  {
   "title": "Issued Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{server=\"$server\", name!=\"\", container!=\"POD\"}) - count(container_tasks_state{server=\"$server\", name!=\"\", state=\"running\"})"
    }
   ]
  },
  {
   "title": "Containers - Network Throughput",
   "type": "table",
   "description": "Carga agregada de red (Suma de RX + TX). Haz clic en el nombre para ver detalles.",
   "gridPos": { "h": 9, "w": 10, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (name) (\n  rate(container_network_receive_bytes_total{server=\"$server\", name!=\"\", container!=\"POD\"}[$__rate_interval]) \n  + \n  rate(container_network_transmit_bytes_total{server=\"$server\", name!=\"\", container!=\"POD\"}[$__rate_interval])\n)"
    }
   ]
  },
  {
   "title": "Containers - Disk I/O Throughput",
   "type": "table",
   "description": "Carga total de disco (Suma de Lectura + Escritura). Haz clic en el nombre para ver detalles.",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (name) (\n  rate(container_fs_reads_bytes_total{server=\"$server\", name!=\"\", container!=\"POD\"}[$__rate_interval]) \n  + \n  rate(container_fs_writes_bytes_total{server=\"$server\", name!=\"\", container!=\"POD\"}[$__rate_interval])\n)"
    }
   ]
  },
  {
   "title": "Avg Container Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(time() - container_start_time_seconds{server=\"$server\", name!=\"\"})"
    }
   ]
  },
  {
   "title": "Last Container Deployment",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - max(container_start_time_seconds{server=\"$server\", name!=\"\", container!=\"POD\"})) * 1000"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Top 20 Containers - CPU Usage (%)",
   "type": "timeseries",
   "description": "Tendencia histórica del uso de CPU del contenedor:\n- Container CPU Trend: Muestra la evolución del consumo de recursos de cómputo específicos del contenedor seleccionado.\n- Interpretación: Permite identificar si un microservicio está experimentando picos inusuales o si requiere un ajuste en sus 'limits' y 'requests' de Docker.\n- Valores esperados: Uso estable dentro de los límites definidos. Un valor cercano al 100% (o al límite del contenedor) indica que el servicio podría presentar latencias por estrangulamiento de CPU (CPU Throttling).",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(20, sum by (name) (rate(container_cpu_usage_seconds_total{server=\"$server\", name!=\"\", container!=\"POD\"}[1m]) * 100))",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "avg(sum by (name) (rate(container_cpu_usage_seconds_total{server=\"$server\", name!=\"\", container!=\"POD\"}[1m]) * 100))",
     "legendFormat": "AVERAGE"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Top 20 Containers - Memory Usage",
   "type": "timeseries",
   "description": "Tendencia histórica del uso de Memoria RAM del contenedor:\n- RAM Usage Trend: Muestra la evolución del consumo de memoria física (Working Set) de los microservicios con mayor carga.\n- Interpretación: Permite identificar fugas de memoria (memory leaks) o si el contenedor está cerca de ser finalizado por el OOM Killer (Out Of Memory).\n- Valores esperados: Consumo estable. Un crecimiento constante sin liberaciones sugiere la necesidad de optimizar el código o aumentar los límites de RAM asignados.",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(20, sum by (name) (container_memory_working_set_bytes{server=\"$server\", name!=\"\", container!=\"POD\"}))",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "avg(sum by (name) (container_memory_working_set_bytes{server=\"$server\", name!=\"\", container!=\"POD\"}))",
     "legendFormat": "AVERAGE"
    }
   ]
  },
  { "title": "Networking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Top 10 Containers - Network Traffic (Mirror)",
   "type": "timeseries",
   "description": "Monitoreo de red en modo espejo:\n- Parte Superior (>0): Tráfico de entrada (IN).\n- Parte Inferior (<0): Tráfico de salida (OUT).",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "topk(7, sum by (name) (rate(container_network_receive_bytes_total{server=\"$server\", name!=\"\", container!=\"POD\"}[1m]) * 8))",
     "legendFormat": "IN: {{name}}"
    },
    {
     "expr": "topk(7, sum by (name) (rate(container_network_transmit_bytes_total{server=\"$server\", name!=\"\", container!=\"POD\"}[1m]) * 8))",
     "legendFormat": "OUT: {{name}}"
    },
    {
     "expr": "avg(sum by (name) (rate(container_network_receive_bytes_total{server=\"$server\", name!=\"\", container!=\"POD\"}[1m]) * 8))",
     "legendFormat": "AVG_IN"
    },
    {
     "expr": "avg(sum by (name) (rate(container_network_transmit_bytes_total{server=\"$server\", name!=\"\", container!=\"POD\"}[1m]) * 8))",
     "legendFormat": "AVG_OUT"
    }
   ]
  },
  { "title": "Disk I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Top 10 Containers - Disk I/O Traffic (Mirror)",
   "type": "timeseries",
   "description": "Monitoreo de lectura y escritura en disco:\n- Parte Superior (>0): Velocidad de Escritura (Write).\n- Parte Inferior (<0): Velocidad de Lectura (Read).",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk(7, sum by (name) (rate(container_fs_writes_bytes_total{server=\"$server\", name!=\"\", container!=\"POD\"}[1m])))",
     "legendFormat": "Write: {{name}}"
    },
    {
     "expr": "topk(7, sum by (name) (rate(container_fs_reads_bytes_total{server=\"$server\", name!=\"\", container!=\"POD\"}[1m])))",
     "legendFormat": "Read: {{name}}"
    },
    {
     "expr": "avg(sum by (name) (rate(container_fs_writes_bytes_total{server=\"$server\", name!=\"\", container!=\"POD\"}[1m])))",
     "legendFormat": "AVG_WRITE"
    },
    {
     "expr": "avg(sum by (name) (rate(container_fs_reads_bytes_total{server=\"$server\", name!=\"\", container!=\"POD\"}[1m])))",
     "legendFormat": "AVG_READ"
    }
   ]
  }
 ]
}