{
 "title": "Template",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "server", "label": "Server", "query": "label_values(up, server)" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "STAT_TITLE",
   "type": "stat",
   "description": "ESTRUCTURA_3_PUNTOS:\n- Definición: \n- Interpretación: \n- Valores esperados: ",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "METRICA{server=\"$server\", service=\"$service\"}"
    }
   ]
  },
  {
   "title": "TIMESERIES_TITLE",
   "type": "timeseries",
   "description": "ESTRUCTURA_3_PUNTOS:\n- Definición: \n- Interpretación: \n- Valores esperados: ",
   "gridPos": { "h": 9, "w": 8, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(METRICA{server=\"$server\"}[$__range]))",
     "legendFormat": "LABEL"
    }
   ]
  },
  {
   "title": "TABLE_TITLE",
   "type": "table",
   "description": "ESTRUCTURA_3_PUNTOS:\n- Definición: \n- Interpretación: \n- Valores esperados: ",
   "gridPos": { "h": 9, "w": 7, "x": 11, "y": 1 },
   "targets": [
    {
     "expr": "METRICA_1{server=\"$server\"}"
    },
    {
     "expr": "METRICA_2{server=\"$server\"}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } }
 ]
}